
export const REGISTER_SUCCESS = "REGISTER_SUCCESS"
export const LOGGED_IN = "LOGGED_IN"
export const UPDATE_USER = "UPDATE USER"
export const UPDATE_UI = "UPDATE UI"
export const UPDATE_THEME = "UPDATE THEME"
export const UPDATE_ANIMALSLEARNT = "UPDATE ANIMALSLEARNT"
export const REGISTER_SOUND = "REGISTER SOUND"
export const UPDATE_SOUND = 'UPDATE SOUND'
export const UPDATE_GAMEDATA = "UPDATE GAMEDATA"
export const UPDATE_PAYMENT = "UPDATE PAYMENT"
export const SHOW_PAYMENT = "SHOW PAYMENT"
