import { ScaledSheet} from "react-native-size-matters";

export default ScaledSheet.create({
  
   container:{
       flex:1,
   },
   toptext:{
       fontSize:"17@ms",
       paddingHorizontal:"20@ms",
       marginTop:"10@ms",
       fontWeight:"bold",
       fontFamily:"NunitoSans-Bold"
   },
   button:{
       borderTopWidth:"1.1@ms",
       width:"95%",
       alignSelf:"center"
   },
   text:{
       fontSize:"20@ms",
       marginVertical:"7@ms",
       marginLeft:"15@ms"
   },
   line:{
      height:"1@ms",
      width:"98%",
      alignSelf:"center",
      marginTop:"20@ms",
      marginBottom:"20@ms"
   },
   activatebutton:{

      height:"40@ms",
      width:"90%",
      justifyContent:"center",
      alignItems:"center",
      backgroundColor:"blue",
      borderRadius:"5@ms",
      alignSelf:"center",
      marginBottom:"15@ms"
   },
   imagewrapper:{
    flex:1,
    justifyContent:"center",
    alignItems:"center",
   },
   bodywrapper:{
      flex:1.5,
      alignItems:"center",
      justifyContent:"center"
   },
   image:{
       marginTop:"30@ms",
       width:'80%',
       height:"90%",
   },
   body:{
       paddingTop:"10@ms",
       fontSize:"16@ms",
       paddingHorizontal:"20@ms",
       paddingBottom:"15@ms",
       fontFamily:"NunitoSans-Regular"
   },
   buttontext:{
       fontSize:"17@ms",
       color:"white",
       fontWeight:"bold"
   },
   backimage:{
       width:"100%",
       height:"100%",
       alignItems:"center",
       justifyContent:"flex-end"
   },
   premiumheader:{
       height:"13%",
       width:'100%',
       justifyContent:"center",
       alignItems:"center"
   },
   premiumtext:{
       fontSize:"16@ms",
       color:"white",
       fontFamily:"NunitoSans-Bold"
   }
   
})